import { Github, CreditCard, Globe, Figma, Server, Smartphone, Cloud, Database, Mail, MessageSquare, Shield, Container, Wallet, Zap, Leaf } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export interface ConnectorSetupStep {
  title: string
  description: string
}

export interface ConnectorConfig {
  name: string
  slug: string
  icon: LucideIcon
  color: string
  authType: 'oauth' | 'api_key' | 'webhook' | 'manual'
  category: 'development' | 'payments' | 'design' | 'infrastructure' | 'communication' | 'analytics'
  description: string
  longDescription: string
  features: string[]
  docsUrl?: string
  status: 'available' | 'coming_soon'
  internalRoute?: string
  apiKeyLabel: string
  apiKeyPlaceholder: string
  apiKeyHelp: string
  apiKeyDocsUrl?: string
  setupSteps: ConnectorSetupStep[]
}

export const connectors: ConnectorConfig[] = [
  {
    name: 'GitHub',
    slug: 'github',
    icon: Github,
    color: '#8B5CF6',
    authType: 'api_key',
    category: 'development',
    description: 'Sincronize repositórios e automatize deploys.',
    longDescription: 'Conecte sua conta do GitHub para sincronizar repositórios, automatizar deploys e gerenciar seu código diretamente da plataforma Vertal.',
    features: ['Sincronização de repositórios', 'Deploy automático', 'Webhooks', 'CI/CD Integration'],
    docsUrl: 'https://docs.github.com',
    status: 'available',
    apiKeyLabel: 'Personal Access Token (PAT)',
    apiKeyPlaceholder: 'ghp_xxxxxxxxxxxxxxxxxxxx',
    apiKeyHelp: 'Crie um Personal Access Token clássico no GitHub com escopos: repo, workflow, read:user.',
    apiKeyDocsUrl: 'https://github.com/settings/tokens/new',
    setupSteps: [
      { title: 'Acesse seu GitHub', description: 'Abra Settings → Developer settings → Personal access tokens (classic).' },
      { title: 'Gere um novo token', description: 'Selecione os escopos: repo, workflow, read:user.' },
      { title: 'Cole o token aqui', description: 'O token será criptografado e armazenado de forma segura na Vertal.' },
    ],
  },
  {
    name: 'Stripe',
    slug: 'stripe',
    icon: CreditCard,
    color: '#635BFF',
    authType: 'api_key',
    category: 'payments',
    description: 'Gerencie pagamentos e assinaturas.',
    longDescription: 'Integre o Stripe Connect para processar pagamentos, gerenciar assinaturas e criar uma marketplace completa.',
    features: ['Pagamentos via cartão', 'Assinaturas', 'Stripe Connect', 'Webhooks de pagamento'],
    docsUrl: 'https://stripe.com/docs',
    status: 'available',
    apiKeyLabel: 'Secret API Key',
    apiKeyPlaceholder: 'sk_live_... ou sk_test_...',
    apiKeyHelp: 'Use uma Secret Key (não a Publishable). Recomendamos uma Restricted Key com escopos mínimos.',
    apiKeyDocsUrl: 'https://dashboard.stripe.com/apikeys',
    setupSteps: [
      { title: 'Abra o Dashboard do Stripe', description: 'Vá até Developers → API Keys.' },
      { title: 'Crie uma Restricted Key', description: 'Marque apenas as permissões necessárias (Charges, Customers, etc).' },
      { title: 'Cole a chave aqui', description: 'A chave será cifrada com AES-256-GCM antes de ser persistida.' },
    ],
  },
  {
    name: 'Figma',
    slug: 'figma',
    icon: Figma,
    color: '#F24E1E',
    authType: 'api_key',
    category: 'design',
    description: 'Importe designs e componentes do Figma.',
    longDescription: 'Conecte o Figma para importar designs, tokens de design e componentes diretamente para seus projetos.',
    features: ['Importar frames', 'Design tokens', 'Auto-layout sync', 'Componentes'],
    docsUrl: 'https://www.figma.com/developers',
    status: 'available',
    apiKeyLabel: 'Personal Access Token',
    apiKeyPlaceholder: 'figd_xxxxxxxxxxxxxxxxxxxx',
    apiKeyHelp: 'Gere um Personal Access Token nas suas configurações do Figma.',
    apiKeyDocsUrl: 'https://www.figma.com/developers/api#access-tokens',
    setupSteps: [
      { title: 'Abra Settings no Figma', description: 'Account → Personal access tokens.' },
      { title: 'Gere um token', description: 'Dê um nome (ex.: "Vertal") e copie o valor exibido.' },
      { title: 'Cole o token aqui', description: 'Você poderá importar arquivos sem mais autenticação.' },
    ],
  },
  {
    name: 'Vercel',
    slug: 'vercel',
    icon: Globe,
    color: '#000000',
    authType: 'api_key',
    category: 'infrastructure',
    description: 'Deploy automático e hosting.',
    longDescription: 'Faça deploy automático dos seus projetos na Vercel com preview deployments e domínios customizados.',
    features: ['Deploy automático', 'Preview URLs', 'Domínios customizados', 'Edge Functions'],
    docsUrl: 'https://vercel.com/docs',
    status: 'available',
    apiKeyLabel: 'Vercel Access Token',
    apiKeyPlaceholder: 'xxxxxxxxxxxxxxxxxxxx',
    apiKeyHelp: 'Crie um Access Token na sua conta Vercel.',
    apiKeyDocsUrl: 'https://vercel.com/account/tokens',
    setupSteps: [
      { title: 'Abra Account Settings', description: 'Vercel → Settings → Tokens.' },
      { title: 'Crie um novo token', description: 'Defina escopo (Full Account ou apenas um Team).' },
      { title: 'Cole o token aqui', description: 'A Vertal usará para automatizar deploys.' },
    ],
  },
  {
    name: 'Supabase',
    slug: 'supabase',
    icon: Database,
    color: '#3ECF8E',
    authType: 'api_key',
    category: 'infrastructure',
    description: 'Backend completo com banco de dados e auth.',
    longDescription: 'Integração nativa com Supabase para autenticação, banco de dados em tempo real, storage e edge functions.',
    features: ['Autenticação', 'Database realtime', 'Storage', 'Edge Functions'],
    status: 'available',
    apiKeyLabel: 'Service Role Key',
    apiKeyPlaceholder: 'eyJhbGciOi...',
    apiKeyHelp: 'Pegue a Service Role Key em Project Settings → API. Nunca exponha essa chave no frontend.',
    apiKeyDocsUrl: 'https://supabase.com/dashboard',
    setupSteps: [
      { title: 'Abra seu projeto Supabase', description: 'Project Settings → API.' },
      { title: 'Copie a Service Role Key', description: 'É a chave que começa com eyJ...' },
      { title: 'Cole aqui', description: 'A Vertal armazena cifrada e usa server-side apenas.' },
    ],
  },
  {
    name: 'Resend',
    slug: 'resend',
    icon: Mail,
    color: '#000000',
    authType: 'api_key',
    category: 'communication',
    description: 'Envie emails transacionais e marketing.',
    longDescription: 'Use o Resend para enviar emails transacionais, campanhas de marketing e notificações com templates customizados.',
    features: ['Emails transacionais', 'Templates React', 'Analytics', 'Domínio customizado'],
    docsUrl: 'https://resend.com/docs',
    status: 'available',
    apiKeyLabel: 'Resend API Key',
    apiKeyPlaceholder: 're_xxxxxxxxxxxx',
    apiKeyHelp: 'Crie uma API Key no painel do Resend.',
    apiKeyDocsUrl: 'https://resend.com/api-keys',
    setupSteps: [
      { title: 'Abra o Resend', description: 'Dashboard → API Keys.' },
      { title: 'Crie uma chave', description: 'Defina permissões (Full access ou Sending only).' },
      { title: 'Cole aqui', description: 'A Vertal enviará emails em seu nome.' },
    ],
  },
  {
    name: 'Gmail',
    slug: 'gmail',
    icon: Mail,
    color: '#EA4335',
    authType: 'oauth',
    category: 'communication',
    description: 'Conecte contas Gmail para ler e enviar emails via IA.',
    longDescription: 'OAuth oficial do Google. Múltiplas contas por usuário, tokens criptografados (AES-256-GCM), leitura e envio com escopos mínimos (gmail.readonly + gmail.send).',
    features: ['OAuth Google', 'Multi-conta', 'Leitura de inbox', 'Envio de email', 'Tokens criptografados'],
    docsUrl: 'https://developers.google.com/gmail/api',
    status: 'available',
    internalRoute: '/connectors/gmail',
    apiKeyLabel: '',
    apiKeyPlaceholder: '',
    apiKeyHelp: 'Conexão via OAuth — não requer chave manual.',
    setupSteps: [
      { title: 'Clique em Conectar conta', description: 'Você será redirecionado ao login do Google.' },
      { title: 'Autorize os escopos', description: 'Leitura (gmail.readonly) e envio (gmail.send).' },
      { title: 'Pronto', description: 'A conta aparece no painel e pode ser usada por agentes IA.' },
    ],
  },
  {
    name: 'Slack',
    slug: 'slack',
    icon: MessageSquare,
    color: '#4A154B',
    authType: 'oauth',
    category: 'communication',
    description: 'Workspaces Slack para mensagens, canais e bots IA.',
    longDescription: 'Conector enterprise via Lovable Gateway. OAuth bot, envio e leitura de mensagens, canais, usuários, threads, blocks. Pronto para agentes IA, automações e dashboards em tempo real.',
    features: ['OAuth bot', 'Envio + threads + blocks', 'Inbox de canais', 'Lista de usuários', 'Logs auditáveis', 'Pronto para agentes IA'],
    docsUrl: 'https://api.slack.com/docs',
    status: 'available',
    internalRoute: '/connectors/slack',
    apiKeyLabel: '',
    apiKeyPlaceholder: '',
    apiKeyHelp: 'Conexão via OAuth gerenciado pela Lovable — sem chaves manuais.',
    setupSteps: [
      { title: 'Conecte o workspace', description: 'Autorize o app Lovable Slack quando solicitado.' },
      { title: 'Ajuste escopos', description: 'Em Connectors → Slack adicione/remova scopes conforme necessário.' },
      { title: 'Pronto', description: 'O bot fica disponível em canais públicos automaticamente.' },
    ],
  },
  {
    name: 'Render',
    slug: 'render',
    icon: Server,
    color: '#46E3B7',
    authType: 'api_key',
    category: 'infrastructure',
    description: 'Deploy, logs, rollback e auto-healing 24/7 dos seus serviços Render.',
    longDescription: 'Connector enterprise multi-tenant para a Render: cole sua API key (cifrada AES-256-GCM), liste serviços, dispare deploys, restart, rollback e ative o motor de auto-healing que monitora health checks e estado de deploy a cada 2 minutos. Inclui hooks para disparar testes E2E via webhook (GitHub Actions).',
    features: ['API key cifrada por usuário', 'Logs streaming', 'Restart/Deploy/Rollback', 'Auto-healing por cron', 'Webhooks E2E pós-deploy', 'Auditoria completa'],
    docsUrl: 'https://api-docs.render.com/',
    status: 'available',
    internalRoute: '/connectors/render',
    apiKeyLabel: 'Render API Key',
    apiKeyPlaceholder: 'rnd_xxxxxxxxxxxxxxxxxxxx',
    apiKeyHelp: 'Crie em dashboard.render.com → Account Settings → API Keys.',
    apiKeyDocsUrl: 'https://dashboard.render.com/u/settings#api-keys',
    setupSteps: [
      { title: 'Abra Account Settings', description: 'Render Dashboard → API Keys.' },
      { title: 'Crie uma API Key', description: 'Copie o token rnd_…' },
      { title: 'Cole no painel', description: 'A Vertal valida e cifra antes de persistir.' },
    ],
  },
  {
    name: 'Discord',
    slug: 'discord',
    icon: MessageSquare,
    color: '#5865F2',
    authType: 'api_key',
    category: 'communication',
    description: 'Bots e notificações no Discord.',
    longDescription: 'Integre com Discord para enviar notificações, criar bots e gerenciar comunidades diretamente da plataforma.',
    features: ['Webhooks', 'Bot commands', 'Notificações', 'Community management'],
    status: 'available',
    apiKeyLabel: 'Bot Token',
    apiKeyPlaceholder: 'MTAxxxxx.xxxxx.xxxxxxxxxxxxxx',
    apiKeyHelp: 'Crie uma aplicação no Discord Developer Portal e copie o Bot Token.',
    apiKeyDocsUrl: 'https://discord.com/developers/applications',
    setupSteps: [
      { title: 'Crie uma aplicação', description: 'Discord Developer Portal → New Application.' },
      { title: 'Adicione um Bot', description: 'Bot → Add Bot → Reset Token.' },
      { title: 'Cole o token aqui', description: 'A Vertal automatizará notificações.' },
    ],
  },
  {
    name: 'Cloudflare',
    slug: 'cloudflare',
    icon: Shield,
    color: '#F38020',
    authType: 'api_key',
    category: 'infrastructure',
    description: 'CDN, DNS e proteção DDoS.',
    longDescription: 'Proteja e acelere seus apps com Cloudflare CDN, gerenciamento de DNS e proteção contra ataques DDoS.',
    features: ['CDN global', 'DNS management', 'DDoS protection', 'Workers'],
    docsUrl: 'https://developers.cloudflare.com',
    status: 'available',
    apiKeyLabel: 'API Token',
    apiKeyPlaceholder: 'xxxxxxxxxxxxxxxxxxxx',
    apiKeyHelp: 'Crie um API Token (não Global API Key) com permissões mínimas necessárias.',
    apiKeyDocsUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    setupSteps: [
      { title: 'Abra seu perfil Cloudflare', description: 'My Profile → API Tokens → Create Token.' },
      { title: 'Use template "Edit zone DNS"', description: 'Ou customize com permissões específicas.' },
      { title: 'Cole o token aqui', description: 'A Vertal gerenciará DNS e cache automaticamente.' },
    ],
  },
  {
    name: 'MongoDB',
    slug: 'mongodb',
    icon: Leaf,
    color: '#13AA52',
    authType: 'api_key',
    category: 'infrastructure',
    description: 'Banco NoSQL escalável e flexível.',
    longDescription: 'Conecte clusters MongoDB Atlas para armazenar documentos, índices vetoriais e dados em tempo real.',
    features: ['Atlas clusters', 'Documentos JSON', 'Vector search', 'Realtime triggers'],
    docsUrl: 'https://www.mongodb.com/docs/atlas/',
    status: 'available',
    apiKeyLabel: 'Connection String',
    apiKeyPlaceholder: 'mongodb+srv://user:pass@cluster.mongodb.net/db',
    apiKeyHelp: 'Use a connection string SRV do seu cluster Atlas. Use um usuário com escopo mínimo.',
    apiKeyDocsUrl: 'https://cloud.mongodb.com/',
    setupSteps: [
      { title: 'Abra o MongoDB Atlas', description: 'Database → Connect → Drivers.' },
      { title: 'Crie um usuário do banco', description: 'Database Access → Add new user (readWrite).' },
      { title: 'Cole a connection string aqui', description: 'A Vertal armazena cifrada e usa server-side apenas.' },
    ],
  },
  {
    name: 'Docker Hub',
    slug: 'docker',
    icon: Container,
    color: '#2496ED',
    authType: 'api_key',
    category: 'infrastructure',
    description: 'Publique e gerencie imagens de containers.',
    longDescription: 'Conecte o Docker Hub para publicar, baixar e versionar imagens de containers usadas nos seus deploys.',
    features: ['Push/pull de imagens', 'Repositórios privados', 'Tags e versões', 'CI/CD integration'],
    docsUrl: 'https://docs.docker.com/docker-hub/',
    status: 'available',
    apiKeyLabel: 'Personal Access Token',
    apiKeyPlaceholder: 'dckr_pat_xxxxxxxxxxxxxxxxxxxx',
    apiKeyHelp: 'Crie um Personal Access Token no Docker Hub com escopo Read/Write.',
    apiKeyDocsUrl: 'https://hub.docker.com/settings/security',
    setupSteps: [
      { title: 'Abra Account Settings', description: 'Docker Hub → Security → New Access Token.' },
      { title: 'Defina o escopo', description: 'Read & Write é recomendado para CI/CD.' },
      { title: 'Cole o token aqui', description: 'A Vertal usará para automatizar publicações.' },
    ],
  },
  {
    name: 'Alchemy',
    slug: 'alchemy',
    icon: Zap,
    color: '#0E76FD',
    authType: 'api_key',
    category: 'infrastructure',
    description: 'Infraestrutura Web3 e RPC para blockchain.',
    longDescription: 'Acesse RPC nodes, Enhanced APIs e ferramentas Web3 da Alchemy para Ethereum, Polygon, Base e mais.',
    features: ['RPC nodes', 'NFT API', 'Webhooks on-chain', 'Multi-chain support'],
    docsUrl: 'https://docs.alchemy.com',
    status: 'available',
    internalRoute: '/connectors/web3/alchemy',
    apiKeyLabel: 'Alchemy API Key',
    apiKeyPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    apiKeyHelp: 'Crie uma App no dashboard da Alchemy e copie a API Key.',
    apiKeyDocsUrl: 'https://dashboard.alchemy.com/apps',
    setupSteps: [
      { title: 'Abra o Dashboard Alchemy', description: 'Apps → Create new App.' },
      { title: 'Selecione a chain', description: 'Ethereum, Polygon, Base, Arbitrum, etc.' },
      { title: 'Cole a API Key aqui', description: 'A Vertal usará para chamadas Web3 server-side.' },
    ],
  },
  {
    name: 'Infura',
    slug: 'infura',
    icon: Zap,
    color: '#FF6B4A',
    authType: 'api_key',
    category: 'infrastructure',
    description: 'RPC EVM tradicional da ConsenSys.',
    longDescription: 'Provedor RPC consolidado para Ethereum, Polygon, Arbitrum, Optimism e mais — multi-chain com SLA enterprise.',
    features: ['RPC EVM', 'Multi-chain', 'WebSockets', 'Archive nodes'],
    docsUrl: 'https://docs.infura.io',
    status: 'available',
    internalRoute: '/connectors/web3/infura',
    apiKeyLabel: 'Infura Project ID',
    apiKeyPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    apiKeyHelp: 'Crie uma API Key (Project ID) em app.infura.io.',
    apiKeyDocsUrl: 'https://app.infura.io',
    setupSteps: [
      { title: 'Abra o Dashboard Infura', description: 'API Keys → Create New Key.' },
      { title: 'Habilite as networks', description: 'Marque Ethereum, Polygon, Arbitrum, etc.' },
      { title: 'Cole o Project ID aqui', description: 'A Vertal usará para chamadas RPC server-side.' },
    ],
  },
  {
    name: 'Custom RPC',
    slug: 'custom-rpc',
    icon: Server,
    color: '#10B981',
    authType: 'manual',
    category: 'infrastructure',
    description: 'Conecte qualquer endpoint RPC próprio.',
    longDescription: 'Plugue QuickNode, Moralis, Chainstack, nó self-hosted ou qualquer endpoint JSON-RPC/REST compatível.',
    features: ['JSON-RPC EVM', 'Solana RPC', 'UTXO REST', 'Bring your own node'],
    docsUrl: 'https://ethereum.org/en/developers/docs/apis/json-rpc/',
    status: 'available',
    internalRoute: '/connectors/web3/custom-rpc',
    apiKeyLabel: 'API Key (opcional)',
    apiKeyPlaceholder: 'Opcional — se sua RPC exigir auth',
    apiKeyHelp: 'Se a chave já vier embutida na URL, deixe vazio.',
    setupSteps: [
      { title: 'Tenha sua RPC URL', description: 'Self-hosted, QuickNode, Moralis, Chainstack, etc.' },
      { title: 'Escolha a network', description: 'EVM, Solana ou UTXO (BTC/LTC/DOGE).' },
      { title: 'Teste e salve', description: 'A Vertal valida com um ping antes de persistir.' },
    ],
  },
  {
    name: 'Web Wallet',
    slug: 'web-wallet',
    icon: Wallet,
    color: '#F6851B',
    authType: 'manual',
    category: 'infrastructure',
    description: 'Conecte uma carteira Web3 (MetaMask, WalletConnect).',
    longDescription: 'Vincule uma carteira Web3 ao seu workspace para assinar transações, deploys de contratos e pagamentos on-chain.',
    features: ['MetaMask', 'WalletConnect', 'Assinatura de transações', 'Deploy de contratos'],
    status: 'coming_soon',
    apiKeyLabel: 'Endereço da carteira',
    apiKeyPlaceholder: '0x0000000000000000000000000000000000000000',
    apiKeyHelp: 'Cole o endereço público da sua carteira. A assinatura é feita pelo cliente, nunca enviamos sua chave privada.',
    setupSteps: [
      { title: 'Abra sua carteira', description: 'MetaMask, Rabby, Coinbase Wallet ou similar.' },
      { title: 'Copie o endereço público', description: 'Começa com 0x e tem 42 caracteres.' },
      { title: 'Cole aqui', description: 'A Vertal solicitará assinatura via WalletConnect quando necessário.' },
    ],
  },
]

export function getConnectorBySlug(slug: string): ConnectorConfig | undefined {
  return connectors.find(c => c.slug === slug)
}

export function getConnectorsByCategory(category: string): ConnectorConfig[] {
  return connectors.filter(c => c.category === category)
}

export const categories = [
  { id: 'all', label: 'Todos' },
  { id: 'development', label: 'Desenvolvimento' },
  { id: 'payments', label: 'Pagamentos' },
  { id: 'design', label: 'Design' },
  { id: 'infrastructure', label: 'Infraestrutura' },
  { id: 'communication', label: 'Comunicação' },
  { id: 'analytics', label: 'Analytics' },
]
